sudo: required

services:
  - docker

language: go
go:
  - "1.13"

before_install:
  - go get github.com/karalabe/xgo

install: go get -d ./...

script: make travisbuild

deploy:
  provider: releases
  api_key:
    secure: "Yom8wSzSSa2XIbK/T7x9QbHt+reYPHseFAmyB3XAcuTOcqbLU79CWfR5XcPPYnn2zhGu5ATQcc6JlKjATHgz3JFn8YxBPxoKNX3Q+K1jsrNMWYfz7uokFzUndvMuQrLYlAYcywaLQgRKIFbTwPAKqEYOET8fzH6Frv+zxiUELfOYiKrnqEb0I6AgkSkH5DM1jQS9GllnciW0J7+4bWIv6cUi02JBQ4Atl3Pq83j2WlpaYIseRoDA+6yJ8bgEc5QTAynx3jTJ1Ok3HKH9XywpWiy59zTI+kaxGPYYoa5Ei1cihhxPTRo0hrRSVxRvnZ5LZopVmXA4+r3FUDyRLlhyxvBEEYjnG7Jh1sEQfpSCmpde+mRrQFvKxbnJjK5UGUatDqV2cxlJmVIOkClYTc0fVS9qBJwjdz+Q3xBkFLchX+L55L8/ZCRm9Qq5OiYQr4RhrbntDE0c0F1KYkY4oi64toAI24X8QdJA5c9FwL4QDqkGt1J+tmFKTDC9cWT1UwtA1d9x55XYyHZ3eRlVM+R0UMeeMNmOKXyJDzy3H5DRSr6UmZCUM/zXo4ip5HNNyXSsMjjkqqC3Zg+OY2kjBMHOwnbIr7cRvnvq5DdUue/L53F0PryumXrfoZ/pg3jv7OhsltAXqZ5GO9b/wYRlfSMrlRo3//c+d5nMHRmd4N4Bzm8="
  file_glob: true
  file:
    - "build/tun2socks*"
  skip_cleanup: true
  on:
    tags: true
